/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DataVizCO2Share: typeof import('./src/components/DataVizCO2Share.vue')['default']
    DataVizMap3DBarBrickKiln: typeof import('./src/components/DataVizMap3DBarBrickKiln.vue')['default']
    DataVizMap3DBarHeatMap: typeof import('./src/components/DataVizMap3DBarHeatMap.vue')['default']
    DataVizMapPie: typeof import('./src/components/DataVizMapPie.vue')['default']
    DataVizPollutantShare: typeof import('./src/components/DataVizPollutantShare.vue')['default']
    DataVizTextReport: typeof import('./src/components/DataVizTextReport.vue')['default']
    DataVizTotaBar: typeof import('./src/components/DataVizTotaBar.vue')['default']
    DataVizTotalTS: typeof import('./src/components/DataVizTotalTS.vue')['default']
    GetData: typeof import('./src/components/GetData.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    LinePlot: typeof import('./src/components/LinePlot.vue')['default']
    MainLine: typeof import('./src/components/MainLine.vue')['default']
    MainMap: typeof import('./src/components/MainMap.vue')['default']
    MainMethodology: typeof import('./src/components/MainMethodology.vue')['default']
    MainReport: typeof import('./src/components/MainReport.vue')['default']
    MainText: typeof import('./src/components/MainText.vue')['default']
    'MainText(sticky_nav)': typeof import('./src/components/MainText(sticky_nav).vue')['default']
    MapboxScatter: typeof import('./src/components/MapboxScatter.vue')['default']
    RefCard: typeof import('./src/components/RefCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMemberCard: typeof import('./src/components/TeamMemberCard.vue')['default']
    Teams: typeof import('./src/components/Teams.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    ThreeDMap: typeof import('./src/components/ThreeDMap.vue')['default']
    VectorMap: typeof import('./src/components/VectorMap.vue')['default']
    WorkPackageCard: typeof import('./src/components/WorkPackageCard.vue')['default']
  }
}
